SELECT
CN.CONTEST_ID,
CN.HACKER_ID, 
CN.NAME, 
SUM(TOTAL_SUBMISSIONS), 
SUM(TOTAL_ACCEPTED_SUBMISSIONS), 
SUM(TOTAL_VIEWS),
SUM(TOTAL_UNIQUE_VIEWS)
FROM CONTESTS CN 
INNER JOIN COLLEGES CL ON (CN.CONTEST_ID = CL.CONTEST_ID)
INNER JOIN CHALLENGES CH ON  (CL.COLLEGE_ID = CH.COLLEGE_ID) 
LEFT JOIN
        (SELECT CHALLENGE_ID, 
         SUM(TOTAL_VIEWS) AS TOTAL_VIEWS, 
         SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
         FROM VIEW_STATS 
         GROUP BY CHALLENGE_ID) VS 
ON (CH.CHALLENGE_ID = VS.CHALLENGE_ID)
LEFT JOIN
        (SELECT CHALLENGE_ID, 
         SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS, 
         SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS 
         FROM SUBMISSION_STATS 
         GROUP BY CHALLENGE_ID) SS 
ON (CH.CHALLENGE_ID = SS.CHALLENGE_ID)
GROUP BY CN.CONTEST_ID, CN.HACKER_ID, CN.NAME
HAVING 
        SUM(TOTAL_SUBMISSIONS)!=0 OR 
        SUM(TOTAL_ACCEPTED_SUBMISSIONS)!=0 OR
        SUM(TOTAL_VIEWS)!=0 OR
        SUM(TOTAL_UNIQUE_VIEWS)!=0
ORDER BY CONTEST_ID;

